### ISSUE TITLE
Access Crawled Data

### ISSUE THREAD

**Issue by yujianll** [notnews/archive_news_cc#1]
Hi, thanks for sharing this data! I wonder how I can access the two crawled datasets. It seems the link in the readme file doesn't work.

**Comment by soodoku** [comment]
hey, the link works but you need to read up on docs. about how to get data from gcp when the 'requestor pays' (it won't be much $). you will generally need to create a project and then you could use the cli to get the data.

**Comment by yujianll** [comment]
@soodoku Thanks for reply. I check this command `gsutil -u PROJECT_IDENTIFIER cp gs://BUCKET_NAME/OBJECT_NAME OBJECT_DESTINATION`. However, I can't find information about your data such as PROJECT_IDENTIFIER, BUCKET_NAME, OBJECT_NAME and so on. Could you point me to some place where I can find such information?

**Comment by soodoku** [comment]
URL = https://storage.googleapis.com/closed-caption-tv-news-archive/archive-cc-2014.csv.xz

bucket_name = closed-caption-tv-news-archive
object_name = archive-cc-2014.csv.xz

**Comment by yujianll** [comment]
Thanks!!
